services:
  - type: web
    name: amplivo-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
    runtime: python3
    pythonVersion: 3.10
